# WikiText-2 KPC-Diverse (K=0.75 + phase noise + freq jitter)
model:
  type: gpt2
  n_layers: 12
  n_heads: 12
  d_model: 768
  vocab_size: null
  max_seq_len: 512
  dropout: 0.1
  attention_dropout: 0.1
  residual_dropout: 0.1
  
  # PhaseAttention enabled
  use_phase_attention: true
  phase_layer_idx: [7]
  num_oscillators: 32
  coupling_strength: 0.75  # Moderate coupling
  natural_freq_std: 0.1
  phase_iterations: 10
  
  # Anti-oversync controls (ENABLED)
  phase_noise_sigma: 0.03  # Add phase noise for diversity
  freq_jitter: 0.02        # Add frequency heterogeneity
  
  # Coherence regularizer (optional)
  coherence_reg:
    enabled: true
    R_target: 0.45
    lambda: 0.1
    mode: ceiling

data:
  dataset: wikitext-2
  seq_len: 512
  train_split: 0.9
  num_workers: 8
  pin_memory: true

training:
  epochs: 50
  batch_size: 8
  lr: 3.0e-4
  weight_decay: 0.01
  grad_clip: 1.0
  
  scheduler:
    type: cosine
    warmup_steps: 500
    min_lr: 1.0e-5
  
  early_stopping:
    enabled: true
    metric: val_ppl
    patience: 5
    min_delta: 0.01

logging:
  log_interval: 100
  eval_interval: 500
  checkpoint_interval: 1000
  r_tracking: true
  r_interval: 500
  save_phase_snapshots: true  # Save phase visualizations

device: cuda
seed: 42

notes: "KPC with diversity push: phase noise + freq jitter + coherence reg"
