name: phasegpt
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip>=23.0

  # PyTorch ecosystem
  - pytorch>=2.0.0
  - pytorch-cuda=11.8  # or 12.1 for newer GPUs
  - torchvision
  - torchaudio

  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.5.0

  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.12.0

  # Jupyter
  - jupyter
  - ipywidgets
  - notebook

  # Development tools
  - black
  - flake8
  - mypy
  - isort
  - pytest
  - pytest-cov

  # Utilities
  - tqdm
  - pyyaml

  # pip-only dependencies
  - pip:
    - transformers>=4.30.0
    - tokenizers>=0.13.0
    - datasets>=2.10.0
    - tensorboard>=2.13.0
    - wandb>=0.15.0
    - omegaconf>=2.3.0
    - plotly>=5.14.0
    - sphinx>=6.0.0
    - sphinx-rtd-theme>=1.2.0
    - pytest-mock>=3.10.0

# Platform-specific notes:
# - For Apple Silicon (M1/M2), use pytorch::pytorch with MPS support
# - For CUDA 12.1, change pytorch-cuda version accordingly
# - For CPU-only: remove pytorch-cuda line
