# Phase A Configuration - Consecutive multi-layer
# Layers 6 and 7, 32 oscillators each, K=1.0 coupling
# Best Val PPL: 4.89 (worse than single-layer)

model:
  type: gpt2
  n_layers: 12
  n_heads: 12
  d_model: 768
  d_ff: 3072
  vocab_size: 65
  max_seq_len: 512
  dropout: 0.1

  # Phase-Coupled Attention Configuration
  use_phase_attention: true
  phase_layer_idx: [6, 7]  # Consecutive layers
  num_oscillators: 32
  coupling_strength: 1.0
  natural_freq: 1.0
  dt: 0.1
  n_sync_steps: 5

training:
  batch_size: 32
  gradient_accumulation_steps: 4
  learning_rate: 3.0e-4
  weight_decay: 0.1
  max_epochs: 20
  warmup_steps: 100
  lr_scheduler: cosine
  grad_clip: 1.0
  patience: 5
  min_delta: 0.001

data:
  dataset: shakespeare
  train_split: 0.9
  val_split: 0.1
  block_size: 512

logging:
  log_interval: 50
  eval_interval: 500
  save_interval: 500
  checkpoint_dir: checkpoints/

experiment:
  name: consecutive_6_7_32osc
  seed: 42
  device: cuda

# Result: Multi-layer provides no benefit over single layer
