# Baseline Configuration - Standard GPT-2 (No Phase Coupling)
# Used for comparison against phase-coupled variants
# Expected Val PPL: 4.97

model:
  type: gpt2
  n_layers: 12
  n_heads: 12
  d_model: 768
  d_ff: 3072
  vocab_size: 65  # char-level Shakespeare
  max_seq_len: 512
  dropout: 0.1

  # No Phase-Coupled Attention
  use_phase_attention: false

training:
  batch_size: 32
  gradient_accumulation_steps: 4
  learning_rate: 3.0e-4
  weight_decay: 0.1
  max_epochs: 164  # Standard training length
  warmup_steps: 100
  lr_scheduler: cosine
  grad_clip: 1.0
  patience: 5
  min_delta: 0.001

data:
  dataset: shakespeare
  train_split: 0.9
  val_split: 0.1
  block_size: 512

logging:
  log_interval: 50
  eval_interval: 500
  save_interval: 500
  checkpoint_dir: checkpoints/

experiment:
  name: baseline_gpt2
  seed: 42
  device: cuda
